package com.uniandes.sgc.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

@DynamoDBTable(tableName = "Sismoss")
public class Sismo {
	 private String id;
	 private String originTime;
	 private String state;
	 private double magnitud;
	 private int profundidadKms;
	 private double longitud;
	 private double latitud;


	 public Sismo() {
		super();
	}

	public Sismo(String originTime, String state, double magnitud, int profundidadKms,
				 double longitud, double latitud) {
		this.originTime = originTime;
		this.state = state;
		this.magnitud = magnitud;
		this.profundidadKms = profundidadKms;
		this.longitud = longitud;
		this.latitud = latitud;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@JsonProperty("origin_time")
	@DynamoDBAttribute(attributeName = "origin_time")
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "origin_time-index")
	public String getOriginTime() {
		return originTime;
	}

	public void setOriginTime(String originTIme) {
		this.originTime = originTIme;
	}

	@JsonProperty("state")
	@DynamoDBAttribute
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@JsonProperty("magnitud")
	@DynamoDBAttribute
	public double getMagnitud() {
		return magnitud;
	}

	public void setMagnitud(double magnitud) {
		this.magnitud = magnitud;
	}

	@JsonProperty("profundidad_kms")
	@DynamoDBAttribute
	public int getProfundidadKms() {
		return profundidadKms;
	}

	public void setProfundidadKms(int profundidadKms) {
		this.profundidadKms = profundidadKms;
	}

	@JsonProperty("longitud")
	@DynamoDBAttribute
	public double getLongitud() {
		return longitud;
	}

	public void setLongitud(double longitud) {
		this.longitud = longitud;
	}

	@JsonProperty("latitud")
	@DynamoDBAttribute
	public double getLatitud() {
		return latitud;
	}

	public void setLatitud(double latitud) {
		this.latitud = latitud;
	}
}
